koalamon_gecko_board_home:
    path:     /p/{project}/admin/geckoboard/
    defaults: { _controller: KoalamonGeckoBoardBundle:Default:index }

koalamon_gecko_board_linechart:
    path:     /geckoboard/linechart/{eventIdentifier}/
    defaults: { _controller: KoalamonGeckoBoardBundle:LineChart:render }

koalamon_gecko_board_number:
    path:     /geckoboard/numberchart/{eventIdentifier}/
    defaults: { _controller: KoalamonGeckoBoardBundle:NumberChart:render }
